#ifndef USER_CONFIG_H
#define USER_CONFIG_H

#define SSID  "YOUR SSID"
#define SSID_PASSWORD  "YOUR SSID PASSWORD"

#define TOKEN "YOUR THING TOKEN HERE"
#define KEEPALIVE 20000

#endif // USER_CONFIG_H
